#!/usr/bin/env bash
# ============================================================
#  01-dropbear.sh — Additional SSH service
# ============================================================

dropbear_install() {
    local port="${1:-143}"

    section "Installing Dropbear alongside OpenSSH"

    install_pkg dropbear

    # Package-native Dropbear service can conflict with OpenSSH or hang via
    # its SysV wrapper. Stop only Dropbear; never touch OpenSSH.
    track_service_state dropbear
    timeout 30 systemctl disable --now dropbear 2>/dev/null || true
    timeout 30 service dropbear stop 2>/dev/null || true

    local conf="/etc/default/dropbear"
    track_file_before_write "$conf"

    log "Configuring Dropbear (port=$port)..."

    cat > "$conf" <<DROPBEAR
# Generated by VPN SSH Installer — $(date)
NO_START=0
DROPBEAR_PORT=${port}
DROPBEAR_EXTRA_ARGS="-K 300 -I 60 -m -b /etc/dropbear.banner"
DROPBEAR_RSAKEY="/etc/dropbear/dropbear_rsa_host_key"
DROPBEAR_ECDSAKEY="/etc/dropbear/dropbear_ecdsa_host_key"
DROPBEAR_ED25519KEY="/etc/dropbear/dropbear_ed25519_host_key"
DROPBEAR_RECEIVE_WINDOW=65536
DROPBEAR_WINDOW_INCREMENT=256
DROPBEAR

    # Generate banner
    track_file_before_write /etc/dropbear.banner
    cat > /etc/dropbear.banner <<'EOF'
  ╔══════════════════════════════════════════╗
  ║  VPN SSH — Dropbear Ready               ║
  ║  Unauthorized access is prohibited      ║
  ╚══════════════════════════════════════════╝
EOF

    # Generate keys
    mkdir -p /etc/dropbear
    if [ ! -s /etc/dropbear/dropbear_rsa_host_key ]; then
        mark_created_file /etc/dropbear/dropbear_rsa_host_key
        log "Generating Dropbear RSA key..."
        timeout 60 dropbearkey -t rsa -s 2048 -f /etc/dropbear/dropbear_rsa_host_key 2>/dev/null || \
            timeout 60 dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key 2>/dev/null || \
            die "Gagal membuat Dropbear RSA host key"
    fi
    if [ ! -s /etc/dropbear/dropbear_ecdsa_host_key ]; then
        mark_created_file /etc/dropbear/dropbear_ecdsa_host_key
        log "Generating Dropbear ECDSA key..."
        timeout 60 dropbearkey -t ecdsa -f /etc/dropbear/dropbear_ecdsa_host_key 2>/dev/null || \
            warn "Gagal membuat ECDSA key; lanjut dengan key lain"
    fi
    if [ ! -s /etc/dropbear/dropbear_ed25519_host_key ]; then
        mark_created_file /etc/dropbear/dropbear_ed25519_host_key
        log "Generating Dropbear Ed25519 key..."
        timeout 60 dropbearkey -t ed25519 -f /etc/dropbear/dropbear_ed25519_host_key 2>/dev/null || \
            warn "Gagal membuat Ed25519 key; lanjut dengan key lain"
    fi

    # Keep existing OpenSSH on port 22 as admin fallback. Dropbear runs on 143.
    # A dedicated simple unit avoids the package's blocking SysV wrapper.
    track_file_before_write /etc/systemd/system/autoscript-dropbear.service
    cat > /etc/systemd/system/autoscript-dropbear.service <<SYSTEMD
[Unit]
Description=AutoScript Dropbear SSH
After=network.target

[Service]
Type=simple
ExecStart=/usr/sbin/dropbear -F -E -K 300 -I 60 -m -w -b /etc/dropbear.banner -p ${port}
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
SYSTEMD

    systemctl daemon-reload 2>/dev/null || true
    enable_service autoscript-dropbear
    sleep 2

    if ! port_in_use "$port"; then
        die "Dropbear gagal listen di port $port; OpenSSH tetap tidak disentuh"
    fi

    log "Dropbear running on port $port; existing OpenSSH remains available"
}