#!/usr/bin/env bash
# ============================================================
#  01-dropbear.sh — Additional SSH service
# ============================================================

dropbear_install() {
    local port="${1:-143}"

    section "Installing Dropbear alongside OpenSSH"

    install_pkg dropbear

    local conf="/etc/default/dropbear"
    backup_file "$conf"

    log "Configuring Dropbear (port=$port)..."

    cat > "$conf" <<DROPBEAR
# Generated by VPN SSH Installer — $(date)
NO_START=0
DROPBEAR_PORT=${port}
DROPBEAR_EXTRA_ARGS="-K 300 -I 60 -m -b /etc/dropbear.banner"
DROPBEAR_RSAKEY="/etc/dropbear/dropbear_rsa_host_key"
DROPBEAR_ECDSAKEY="/etc/dropbear/dropbear_ecdsa_host_key"
DROPBEAR_ED25519KEY="/etc/dropbear/dropbear_ed25519_host_key"
DROPBEAR_RECEIVE_WINDOW=65536
DROPBEAR_WINDOW_INCREMENT=256
DROPBEAR

    # Generate banner
    cat > /etc/dropbear.banner <<'EOF'
  ╔══════════════════════════════════════════╗
  ║  VPN SSH — Dropbear Ready               ║
  ║  Unauthorized access is prohibited      ║
  ╚══════════════════════════════════════════╝
EOF

    # Generate keys
    if [ ! -f /etc/dropbear/dropbear_rsa_host_key ]; then
        log "Generating Dropbear RSA key..."
        dropbearkey -t rsa -s 2048 -f /etc/dropbear/dropbear_rsa_host_key 2>/dev/null || \
            dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key 2>/dev/null || true
    fi
    if [ ! -f /etc/dropbear/dropbear_ecdsa_host_key ]; then
        log "Generating Dropbear ECDSA key..."
        dropbearkey -t ecdsa -f /etc/dropbear/dropbear_ecdsa_host_key 2>/dev/null || true
    fi
    if [ ! -f /etc/dropbear/dropbear_ed25519_host_key ]; then
        log "Generating Dropbear Ed25519 key..."
        dropbearkey -t ed25519 -f /etc/dropbear/dropbear_ed25519_host_key 2>/dev/null || true
    fi

    # Keep existing OpenSSH on port 22 as admin fallback.
    # Dropbear runs alongside it on port 143.
    enable_service dropbear

    if ! port_in_use "$port"; then
        die "Dropbear gagal listen di port $port; OpenSSH tetap tidak disentuh"
    fi

    log "Dropbear running on port $port; existing OpenSSH remains available"
}