#!/usr/bin/env bash
# ============================================================
#  dropbear.sh — Dropbear lightweight SSH install + config
# ============================================================

dropbear_install() {
    local port="${1:-143}"

    section "Installing Dropbear"

    install_pkg dropbear

    local conf="/etc/default/dropbear"
    backup_file "$conf"

    log "Configuring Dropbear (port=$port)..."

    cat > "$conf" <<DROPBEAR
# Generated by VPN SSH Installer — $(date)
NO_START=0
DROPBEAR_PORT=${port}
DROPBEAR_EXTRA_ARGS="-K 300 -I 60 -m -s -g -b /etc/dropbear.banner"
DROPBEAR_RSAKEY="/etc/dropbear/dropbear_rsa_host_key"
DROPBEAR_ECDSAKEY="/etc/dropbear/dropbear_ecdsa_host_key"
DROPBEAR_ED25519KEY="/etc/dropbear/dropbear_ed25519_host_key"
DROPBEAR_RECEIVE_WINDOW=65536
DROPBEAR_WINDOW_INCREMENT=256
DROPBEAR

    # Generate banner
    cat > /etc/dropbear.banner <<'EOF'
  ╔══════════════════════════════════════════╗
  ║  VPN SSH — Dropbear Ready               ║
  ║  Unauthorized access is prohibited      ║
  ╚══════════════════════════════════════════╝
EOF

    # Generate keys
    if [ ! -f /etc/dropbear/dropbear_rsa_host_key ]; then
        log "Generating Dropbear RSA key..."
        dropbearkey -t rsa -s 2048 -f /etc/dropbear/dropbear_rsa_host_key 2>/dev/null || \
            dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key 2>/dev/null || true
    fi
    if [ ! -f /etc/dropbear/dropbear_ecdsa_host_key ]; then
        log "Generating Dropbear ECDSA key..."
        dropbearkey -t ecdsa -f /etc/dropbear/dropbear_ecdsa_host_key 2>/dev/null || true
    fi
    if [ ! -f /etc/dropbear/dropbear_ed25519_host_key ]; then
        log "Generating Dropbear Ed25519 key..."
        dropbearkey -t ed25519 -f /etc/dropbear/dropbear_ed25519_host_key 2>/dev/null || true
    fi

    enable_service dropbear

    if port_in_use "$port"; then
        log "Dropbear running on port $port ✓"
    else
        warn "Dropbear mungkin tidak listen di port $port — cek manual"
    fi
}