#!/usr/bin/env bash
# ============================================================
#  05-firewall.sh — iptables + Fail2Ban
# ============================================================

firewall_setup() {
    local dropbear_port="${1:-143}"
    local ws_port="${2:-8880}"
    local badvpn_start="${3:-7300}"
    local badvpn_end="${4:-7300}"

    section "iptables + Fail2Ban Setup"

    # Provider VPS handles inbound port policy through its web portal.
    install_pkg fail2ban
    install_pkg iptables
    log "UFW tidak digunakan; port dikelola lewat portal provider VPS"

    # Preserve complete pre-install ruleset. Uninstall restores it instead of
    # deleting provider/admin firewall rules.
    local firewall_backup="${AUTOSCRIPT_ROOT}/data/iptables.before.v4"
    if [ ! -s "$firewall_backup" ] && command -v iptables-save >/dev/null 2>&1; then
        mkdir -p "$(dirname "$firewall_backup")"
        iptables-save > "$firewall_backup" 2>/dev/null || true
        chmod 600 "$firewall_backup"
    fi
    track_file_before_write /etc/iptables/rules.v4

    # ── iptables Rate Limiting ─────────────────────────────
    log "Configuring iptables rate limiting..."
    local rate_chain="AUTOSCRIPT_RATE_SSH"
    local invalid_chain="AUTOSCRIPT_INVALID"

    iptables -N "$rate_chain" 2>/dev/null || iptables -F "$rate_chain" 2>/dev/null || true
    iptables -A "$rate_chain" -m recent --set --name AUTOSCRIPT_SSH --rsource 2>/dev/null || true
    iptables -A "$rate_chain" -m recent --update --seconds 60 --hitcount 10 \
        --name AUTOSCRIPT_SSH --rsource -j DROP 2>/dev/null || true
    iptables -A "$rate_chain" -j ACCEPT 2>/dev/null || true
    iptables -C INPUT -p tcp --syn --dport "$dropbear_port" -m conntrack --ctstate NEW \
        -j "$rate_chain" 2>/dev/null || \
        iptables -I INPUT -p tcp --syn --dport "$dropbear_port" -m conntrack --ctstate NEW \
        -j "$rate_chain" 2>/dev/null || true

    iptables -N "$invalid_chain" 2>/dev/null || iptables -F "$invalid_chain" 2>/dev/null || true
    iptables -A "$invalid_chain" -j DROP 2>/dev/null || true
    iptables -C INPUT -m conntrack --ctstate INVALID -j "$invalid_chain" 2>/dev/null || \
        iptables -I INPUT -m conntrack --ctstate INVALID -j "$invalid_chain" 2>/dev/null || true

    if command -v iptables-save >/dev/null 2>&1; then
        mkdir -p /etc/iptables
        iptables-save > /etc/iptables/rules.v4 2>/dev/null || true
    fi

    # Install iptables-persistent for reboot survival
    install_pkg iptables-persistent 2>/dev/null || true

    log "iptables rate limiting applied"

    # ── Fail2Ban ───────────────────────────────────────────
    log "Configuring Fail2Ban..."

    # Preserve existing config or mark generated file for cleanup.
    track_file_before_write /etc/fail2ban/jail.local

    cat > /etc/fail2ban/jail.local <<FAIL2BAN
# Generated by VPN SSH Installer — $(date)
[DEFAULT]
bantime   = 3600
findtime  = 600
maxretry  = 4
destemail = root@localhost
action    = %(action_)s
backend   = auto

[dropbear]

enabled   = true
port      = ${dropbear_port}
filter    = dropbear
logpath   = /var/log/auth.log
maxretry  = 4
bantime   = 3600

FAIL2BAN

    # Configure HAProxy logging for Fail2Ban
    if [ -f /etc/rsyslog.d/49-haproxy.conf ] || [ ! -f /etc/rsyslog.d/haproxy.conf ]; then
        track_file_before_write /etc/rsyslog.d/haproxy.conf
        cat > /etc/rsyslog.d/haproxy.conf <<'RSYSLOG'
$AddUnixListenSocket /var/lib/haproxy/dev/log
:programname, startswith, "haproxy" {
    /var/log/haproxy.log
    stop
}
RSYSLOG
        systemctl restart rsyslog 2>/dev/null || true
    fi

    enable_service fail2ban
    log "Fail2Ban configured and running"
}