#!/usr/bin/env bash
# ============================================================
#  05-firewall.sh — iptables + Fail2Ban
# ============================================================

firewall_setup() {
    local dropbear_port="${1:-22}"
    local ws_port="${2:-8880}"
    local badvpn_start="${3:-7300}"
    local badvpn_end="${4:-7300}"

    section "iptables + Fail2Ban Setup"

    # Provider VPS handles inbound port policy through its web portal.
    install_pkg fail2ban
    install_pkg iptables
    log "UFW tidak digunakan; port dikelola lewat portal provider VPS"

    # ── iptables Rate Limiting ─────────────────────────────
    log "Configuring iptables rate limiting..."

    # Rate limit SSH — 10 connections per minute per IP
    iptables -N RATE_SSH 2>/dev/null || iptables -F RATE_SSH 2>/dev/null || true
    iptables -A RATE_SSH \
        -m recent --set --name SSH_RATE --rsource 2>/dev/null || true
    iptables -A RATE_SSH \
        -m recent --update --seconds 60 --hitcount 10 --name SSH_RATE --rsource \
        -j DROP 2>/dev/null || true
    iptables -A RATE_SSH -j ACCEPT 2>/dev/null || true

    # Apply rate limiting to primary Dropbear SSH port.
    iptables -I INPUT -p tcp --dport "$dropbear_port" -j RATE_SSH 2>/dev/null || true

    # Drop invalid packets
    iptables -A INPUT -m state --state INVALID -j DROP 2>/dev/null || true

    # Save iptables rules
    if command -v iptables-save &>/dev/null; then
        mkdir -p /etc/iptables
        iptables-save > /etc/iptables/rules.v4 2>/dev/null || true
    fi

    # Install iptables-persistent for reboot survival
    install_pkg iptables-persistent 2>/dev/null || true

    log "iptables rate limiting applied"

    # ── Fail2Ban ───────────────────────────────────────────
    log "Configuring Fail2Ban..."

    # Backup existing config
    backup_file /etc/fail2ban/jail.local

    cat > /etc/fail2ban/jail.local <<FAIL2BAN
# Generated by VPN SSH Installer — $(date)
[DEFAULT]
bantime   = 3600
findtime  = 600
maxretry  = 4
destemail = root@localhost
action    = %(action_)s
backend   = auto

[dropbear]

enabled   = true
port      = ${dropbear_port}
filter    = sshd
logpath   = /var/log/auth.log
maxretry  = 4
bantime   = 3600

[haproxy-http]
enabled   = true
port      = 80,443
filter    = haproxy-http-auth
logpath   = /var/log/haproxy.log
maxretry  = 5
bantime   = 3600
FAIL2BAN

    # Configure HAProxy logging for Fail2Ban
    if [ -f /etc/rsyslog.d/49-haproxy.conf ] || [ ! -f /etc/rsyslog.d/haproxy.conf ]; then
        cat > /etc/rsyslog.d/haproxy.conf <<'RSYSLOG'
$AddUnixListenSocket /var/lib/haproxy/dev/log
:programname, startswith, "haproxy" {
    /var/log/haproxy.log
    stop
}
RSYSLOG
        systemctl restart rsyslog 2>/dev/null || true
    fi

    enable_service fail2ban
    log "Fail2Ban configured and running"
}