#!/usr/bin/env bash
# ============================================================
#  firewall.sh — UFW + iptables + Fail2Ban
# ============================================================

firewall_setup() {
    local ssh_port="${1:-22}"
    local dropbear_port="${2:-143}"
    local ws_port="${3:-8880}"
    local badvpn_start="${4:-7300}"
    local badvpn_end="${5:-7399}"
    local haproxy_ports=("${@:6}")

    section "Firewall + Fail2Ban Setup"

    # ── Install packages ───────────────────────────────────
    install_pkg ufw
    install_pkg fail2ban
    install_pkg iptables

    # ── UFW ────────────────────────────────────────────────
    log "Configuring UFW..."

    ufw --force reset 2>/dev/null || true

    # Default policies
    ufw default deny incoming 2>/dev/null || true
    ufw default allow outgoing 2>/dev/null || true

    # SSH
    ufw allow "$ssh_port/tcp" comment "OpenSSH" 2>/dev/null || true

    # Dropbear
    [ -n "$dropbear_port" ] && ufw allow "$dropbear_port/tcp" comment "Dropbear" 2>/dev/null || true

    # HAProxy ports
    ufw allow 80/tcp comment "HAProxy HTTP" 2>/dev/null || true
    ufw allow 443/tcp comment "HAProxy HTTPS" 2>/dev/null || true

    # WS tunnel (internal, tapi allow untuk direct access)
    ufw allow "$ws_port/tcp" comment "WS Tunnel" 2>/dev/null || true

    # BadVPN UDP range
    ufw allow "${badvpn_start}:${badvpn_end}/udp" comment "BadVPN UDPGW" 2>/dev/null || true

    # Admin
    ufw allow 9090/tcp comment "HAProxy Stats" 2>/dev/null || true

    # Enable
    ufw --force enable 2>/dev/null || true
    log "UFW enabled"

    # ── iptables Rate Limiting ─────────────────────────────
    log "Configuring iptables rate limiting..."

    # Rate limit SSH — 10 connections per minute per IP
    iptables -N RATE_SSH 2>/dev/null || iptables -F RATE_SSH 2>/dev/null || true
    iptables -A RATE_SSH \
        -m recent --set --name SSH_RATE --rsource 2>/dev/null || true
    iptables -A RATE_SSH \
        -m recent --update --seconds 60 --hitcount 10 --name SSH_RATE --rsource \
        -j DROP 2>/dev/null || true
    iptables -A RATE_SSH -j ACCEPT 2>/dev/null || true

    # Apply rate limiting to SSH ports
    for port in "$ssh_port" "$dropbear_port"; do
        iptables -I INPUT -p tcp --dport "$port" -j RATE_SSH 2>/dev/null || true
    done

    # Drop invalid packets
    iptables -A INPUT -m state --state INVALID -j DROP 2>/dev/null || true

    # Save iptables rules
    if command -v iptables-save &>/dev/null; then
        mkdir -p /etc/iptables
        iptables-save > /etc/iptables/rules.v4 2>/dev/null || true
    fi

    # Install iptables-persistent for reboot survival
    install_pkg iptables-persistent 2>/dev/null || true

    log "iptables rate limiting applied"

    # ── Fail2Ban ───────────────────────────────────────────
    log "Configuring Fail2Ban..."

    # Backup existing config
    backup_file /etc/fail2ban/jail.local

    cat > /etc/fail2ban/jail.local <<FAIL2BAN
# Generated by VPN SSH Installer — $(date)
[DEFAULT]
bantime   = 3600
findtime  = 600
maxretry  = 4
destemail = root@localhost
action    = %(action_)s
backend   = auto

[sshd]
enabled   = true
port      = ${ssh_port}
filter    = sshd
logpath   = /var/log/auth.log
maxretry  = 4
bantime   = 3600

[sshd-ddos]
enabled   = true
port      = ${ssh_port}
filter    = sshd-ddos
logpath   = /var/log/auth.log
maxretry  = 8
bantime   = 7200

[dropbear]
enabled   = true
port      = ${dropbear_port}
filter    = sshd
logpath   = /var/log/auth.log
maxretry  = 4
bantime   = 3600

[haproxy-http]
enabled   = true
port      = 80,443
filter    = haproxy-http-auth
logpath   = /var/log/haproxy.log
maxretry  = 5
bantime   = 3600
FAIL2BAN

    # Configure HAProxy logging for Fail2Ban
    if [ -f /etc/rsyslog.d/49-haproxy.conf ] || [ ! -f /etc/rsyslog.d/haproxy.conf ]; then
        cat > /etc/rsyslog.d/haproxy.conf <<'RSYSLOG'
$AddUnixListenSocket /var/lib/haproxy/dev/log
:programname, startswith, "haproxy" {
    /var/log/haproxy.log
    stop
}
RSYSLOG
        systemctl restart rsyslog 2>/dev/null || true
    fi

    enable_service fail2ban
    log "Fail2Ban configured and running"
}