#!/usr/bin/env bash
# ============================================================
#  openssh.sh — OpenSSH install + hardening
# ============================================================

openssh_install() {
    local port="${1:-22}"
    local allow_root="${2:-yes}"
    local allow_pass="${3:-yes}"

    section "Installing OpenSSH"
    install_pkg openssh-server
    install_pkg openssh-client

    local conf="/etc/ssh/sshd_config"
    backup_file "$conf"

    log "Configuring OpenSSH (port=$port root=$allow_root password=$allow_pass)..."

    cat > "$conf" <<SSHD
# Generated by VPN SSH Installer — $(date)
# Original: ${conf}.bak-*

Port ${port}
AddressFamily inet
ListenAddress 0.0.0.0

# Auth
PermitRootLogin ${allow_root}
PasswordAuthentication $( [ "$allow_pass" = "yes" ] && echo "yes" || echo "no" )
PubkeyAuthentication yes
ChallengeResponseAuthentication no
UsePAM yes
KerberosAuthentication no
GSSAPIAuthentication no

# Protocol
Protocol 2
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

# Security
PermitEmptyPasswords no
MaxAuthTries 5
MaxSessions 15
MaxStartups 20:50:50
ClientAliveInterval 300
ClientAliveCountMax 2
LoginGraceTime 60
StrictModes yes
AllowTcpForwarding yes
GatewayPorts yes
PermitTunnel yes

# Logging
SyslogFacility AUTH
LogLevel VERBOSE

# Extra
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
Compression yes

# Subsystem
Subsystem sftp /usr/lib/openssh/sftp-server

# Banner
Banner /etc/issue.net
SSHD

    # Generate banner
    cat > /etc/issue.net <<'EOF'
  ╔══════════════════════════════════════════╗
  ║  VPN SSH — Tunneling Ready              ║
  ║  Unauthorized access is prohibited      ║
  ╚══════════════════════════════════════════╝
EOF

    # Generate host keys if missing
    for key in rsa ecdsa ed25519; do
        if [ ! -f "/etc/ssh/ssh_host_${key}_key" ]; then
            log "Generating ${key} host key..."
            ssh-keygen -t "$key" -f "/etc/ssh/ssh_host_${key}_key" -N "" -q
        fi
    done

    # Restart
    enable_service ssh
    enable_service sshd

    # Verify
    if port_in_use "$port"; then
        log "OpenSSH running on port $port ✓"
    else
        warn "OpenSSH mungkin tidak listen di port $port — cek manual"
    fi
}