# Generated by VPN SSH Installer
# Port sharing: SSH Direct, SSH over SSL/TLS, SSH over WS/WSS
# Certificate: {{CERT_TYPE}}

global
    log /dev/log local0
    log /dev/log local1 notice
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon
    maxconn {{MAXCONN}}
    tune.ssl.default-dh-param 2048
    ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11

defaults
    log global
    mode tcp
    option dontlognull
    option tcplog
    timeout connect 10s
    timeout client 1800s
    timeout server 1800s
    timeout tunnel 3600s
    timeout client-fin 30s
    timeout server-fin 30s

listen stats
    bind 127.0.0.1:9090
    mode http
    stats enable
    stats uri /stats
    stats realm HAProxy\ Stats
    stats auth admin:{{STATS_PASSWORD}}
    stats refresh 10s

frontend http-in
    bind :{{PORT_80}}
    mode tcp
    option tcplog
    tcp-request inspect-delay 3s
    tcp-request content accept if { req.payload(0,4) -m str SSH- }
    tcp-request content accept if { req.payload(0,3) -m str GET }
    tcp-request content accept if { req.payload(0,4) -m str POST }
    tcp-request content accept if { req.payload(0,4) -m str CONN }
    tcp-request content accept if { req.payload(0,7) -m str OPTIONS }
    tcp-request content accept if { req.payload(0,4) -m str HEAD }
    tcp-request content accept if { req.payload(0,4) -m str PUT }
    tcp-request content accept if { req.payload(0,6) -m str DELETE }
    tcp-request content accept if { req.payload(0,5) -m str PATCH }
    default_backend ssh_direct
    use_backend ssh_direct if { req.payload(0,4) -m str SSH- }
    use_backend ws_tunnel_plain if HTTP
    use_backend ws_tunnel_plain if { req.payload(0,3) -m str GET }
    use_backend ws_tunnel_plain if { req.payload(0,4) -m str POST }

frontend https-in
    bind :{{PORT_443}} ssl crt {{CERT_PEM}} alpn h2,http/1.1
    mode tcp
    option tcplog
    tcp-request inspect-delay 3s
    tcp-request content accept if { req.payload(0,4) -m str SSH- }
    tcp-request content accept if { req.payload(0,3) -m str GET }
    default_backend ws_tunnel_ssl
    use_backend ssh_local if { req.payload(0,4) -m str SSH- }
    use_backend ws_tunnel_ssl if HTTP
    use_backend ws_tunnel_ssl if { req.payload(0,3) -m str GET }

backend ssh_direct
    mode tcp
    server dropbear1 127.0.0.1:{{DROPBEAR_PORT}} check inter 10s fall 3 rise 2
    timeout server 3600s

backend ssh_local
    mode tcp
    server dropbear1 127.0.0.1:{{DROPBEAR_PORT}} check inter 10s fall 3 rise 2
    timeout server 3600s

backend ws_tunnel_plain
    mode tcp
    option tcp-check
    server ws1 127.0.0.1:{{WS_PORT}} check inter 10s fall 3 rise 2
    timeout server 3600s
    timeout tunnel 3600s

backend ws_tunnel_ssl
    mode tcp
    option tcp-check
    server ws1 127.0.0.1:{{WS_PORT}} check inter 10s fall 3 rise 2
    timeout server 3600s
    timeout tunnel 3600s
